/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CryptoAPIs.Api;
using CryptoAPIs.Model;
using CryptoAPIs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CryptoAPIs.Test.Model
{
    /// <summary>
    ///  Class for testing GetBlockDetailsByBlockHeightFromCallbackRI
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetBlockDetailsByBlockHeightFromCallbackRITests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetBlockDetailsByBlockHeightFromCallbackRI
        //private GetBlockDetailsByBlockHeightFromCallbackRI instance;

        public GetBlockDetailsByBlockHeightFromCallbackRITests()
        {
            // TODO uncomment below to create an instance of GetBlockDetailsByBlockHeightFromCallbackRI
            //instance = new GetBlockDetailsByBlockHeightFromCallbackRI();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetBlockDetailsByBlockHeightFromCallbackRI
        /// </summary>
        [Fact]
        public void GetBlockDetailsByBlockHeightFromCallbackRIInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetBlockDetailsByBlockHeightFromCallbackRI
            //Assert.IsType<GetBlockDetailsByBlockHeightFromCallbackRI>(instance);
        }


        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Fact]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'PreviousBlockHash'
        /// </summary>
        [Fact]
        public void PreviousBlockHashTest()
        {
            // TODO unit test for the property 'PreviousBlockHash'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'TransactionsCount'
        /// </summary>
        [Fact]
        public void TransactionsCountTest()
        {
            // TODO unit test for the property 'TransactionsCount'
        }
        /// <summary>
        /// Test the property 'BlockchainSpecific'
        /// </summary>
        [Fact]
        public void BlockchainSpecificTest()
        {
            // TODO unit test for the property 'BlockchainSpecific'
        }

    }

}
