/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CryptoAPIs.Api;
using CryptoAPIs.Model;
using CryptoAPIs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CryptoAPIs.Test.Model
{
    /// <summary>
    ///  Class for testing GetWalletAssetDetailsRINonFungibleTokensInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWalletAssetDetailsRINonFungibleTokensInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWalletAssetDetailsRINonFungibleTokensInner
        //private GetWalletAssetDetailsRINonFungibleTokensInner instance;

        public GetWalletAssetDetailsRINonFungibleTokensInnerTests()
        {
            // TODO uncomment below to create an instance of GetWalletAssetDetailsRINonFungibleTokensInner
            //instance = new GetWalletAssetDetailsRINonFungibleTokensInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWalletAssetDetailsRINonFungibleTokensInner
        /// </summary>
        [Fact]
        public void GetWalletAssetDetailsRINonFungibleTokensInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWalletAssetDetailsRINonFungibleTokensInner
            //Assert.IsType<GetWalletAssetDetailsRINonFungibleTokensInner>(instance);
        }


        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Fact]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
