/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CryptoAPIs.Api;
using CryptoAPIs.Model;
using CryptoAPIs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CryptoAPIs.Test.Model
{
    /// <summary>
    ///  Class for testing ListTransactionsByBlockHashRIBSBCVoutInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListTransactionsByBlockHashRIBSBCVoutInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListTransactionsByBlockHashRIBSBCVoutInner
        //private ListTransactionsByBlockHashRIBSBCVoutInner instance;

        public ListTransactionsByBlockHashRIBSBCVoutInnerTests()
        {
            // TODO uncomment below to create an instance of ListTransactionsByBlockHashRIBSBCVoutInner
            //instance = new ListTransactionsByBlockHashRIBSBCVoutInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListTransactionsByBlockHashRIBSBCVoutInner
        /// </summary>
        [Fact]
        public void ListTransactionsByBlockHashRIBSBCVoutInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListTransactionsByBlockHashRIBSBCVoutInner
            //Assert.IsType<ListTransactionsByBlockHashRIBSBCVoutInner>(instance);
        }


        /// <summary>
        /// Test the property 'IsSpent'
        /// </summary>
        [Fact]
        public void IsSpentTest()
        {
            // TODO unit test for the property 'IsSpent'
        }
        /// <summary>
        /// Test the property 'ScriptPubKey'
        /// </summary>
        [Fact]
        public void ScriptPubKeyTest()
        {
            // TODO unit test for the property 'ScriptPubKey'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
