/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CryptoAPIs.Api;
using CryptoAPIs.Model;
using CryptoAPIs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CryptoAPIs.Test.Model
{
    /// <summary>
    ///  Class for testing ListTransactionsByAddressRIBSD2Vout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListTransactionsByAddressRIBSD2VoutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListTransactionsByAddressRIBSD2Vout
        //private ListTransactionsByAddressRIBSD2Vout instance;

        public ListTransactionsByAddressRIBSD2VoutTests()
        {
            // TODO uncomment below to create an instance of ListTransactionsByAddressRIBSD2Vout
            //instance = new ListTransactionsByAddressRIBSD2Vout();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListTransactionsByAddressRIBSD2Vout
        /// </summary>
        [Fact]
        public void ListTransactionsByAddressRIBSD2VoutInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListTransactionsByAddressRIBSD2Vout
            //Assert.IsType<ListTransactionsByAddressRIBSD2Vout>(instance);
        }


        /// <summary>
        /// Test the property 'IsSpent'
        /// </summary>
        [Fact]
        public void IsSpentTest()
        {
            // TODO unit test for the property 'IsSpent'
        }
        /// <summary>
        /// Test the property 'ScriptPubKey'
        /// </summary>
        [Fact]
        public void ScriptPubKeyTest()
        {
            // TODO unit test for the property 'ScriptPubKey'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
