/*
 * CryptoAPIs
 *
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CryptoAPIs.Api;
using CryptoAPIs.Model;
using CryptoAPIs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CryptoAPIs.Test.Model
{
    /// <summary>
    ///  Class for testing ListDepositAddressesRIFungibleTokensInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListDepositAddressesRIFungibleTokensInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListDepositAddressesRIFungibleTokensInner
        //private ListDepositAddressesRIFungibleTokensInner instance;

        public ListDepositAddressesRIFungibleTokensInnerTests()
        {
            // TODO uncomment below to create an instance of ListDepositAddressesRIFungibleTokensInner
            //instance = new ListDepositAddressesRIFungibleTokensInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListDepositAddressesRIFungibleTokensInner
        /// </summary>
        [Fact]
        public void ListDepositAddressesRIFungibleTokensInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListDepositAddressesRIFungibleTokensInner
            //Assert.IsType<ListDepositAddressesRIFungibleTokensInner>(instance);
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Identifier'
        /// </summary>
        [Fact]
        public void IdentifierTest()
        {
            // TODO unit test for the property 'Identifier'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'TokenDecimals'
        /// </summary>
        [Fact]
        public void TokenDecimalsTest()
        {
            // TODO unit test for the property 'TokenDecimals'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
