/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: developers@cryptoapis.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CryptoAPIs.Api;
using CryptoAPIs.Model;
using CryptoAPIs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CryptoAPIs.Test.Model
{
    /// <summary>
    ///  Class for testing ListWalletTransactionsRI
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListWalletTransactionsRITests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListWalletTransactionsRI
        //private ListWalletTransactionsRI instance;

        public ListWalletTransactionsRITests()
        {
            // TODO uncomment below to create an instance of ListWalletTransactionsRI
            //instance = new ListWalletTransactionsRI();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListWalletTransactionsRI
        /// </summary>
        [Fact]
        public void ListWalletTransactionsRIInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListWalletTransactionsRI
            //Assert.IsType<ListWalletTransactionsRI>(instance);
        }


        /// <summary>
        /// Test the property 'Direction'
        /// </summary>
        [Fact]
        public void DirectionTest()
        {
            // TODO unit test for the property 'Direction'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'FungibleTokens'
        /// </summary>
        [Fact]
        public void FungibleTokensTest()
        {
            // TODO unit test for the property 'FungibleTokens'
        }
        /// <summary>
        /// Test the property 'InternalTransactions'
        /// </summary>
        [Fact]
        public void InternalTransactionsTest()
        {
            // TODO unit test for the property 'InternalTransactions'
        }
        /// <summary>
        /// Test the property 'NonFungibleTokens'
        /// </summary>
        [Fact]
        public void NonFungibleTokensTest()
        {
            // TODO unit test for the property 'NonFungibleTokens'
        }
        /// <summary>
        /// Test the property 'Recipients'
        /// </summary>
        [Fact]
        public void RecipientsTest()
        {
            // TODO unit test for the property 'Recipients'
        }
        /// <summary>
        /// Test the property 'Senders'
        /// </summary>
        [Fact]
        public void SendersTest()
        {
            // TODO unit test for the property 'Senders'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
