/*
 * Crypto APIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: bizdev@cryptoapis.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAutomaticCoinsForwardingRequestBodyDataItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAutomaticCoinsForwardingRequestBodyDataItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAutomaticCoinsForwardingRequestBodyDataItem
        //private CreateAutomaticCoinsForwardingRequestBodyDataItem instance;

        public CreateAutomaticCoinsForwardingRequestBodyDataItemTests()
        {
            // TODO uncomment below to create an instance of CreateAutomaticCoinsForwardingRequestBodyDataItem
            //instance = new CreateAutomaticCoinsForwardingRequestBodyDataItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAutomaticCoinsForwardingRequestBodyDataItem
        /// </summary>
        [Fact]
        public void CreateAutomaticCoinsForwardingRequestBodyDataItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAutomaticCoinsForwardingRequestBodyDataItem
            //Assert.IsType<CreateAutomaticCoinsForwardingRequestBodyDataItem>(instance);
        }


        /// <summary>
        /// Test the property 'CallbackSecretKey'
        /// </summary>
        [Fact]
        public void CallbackSecretKeyTest()
        {
            // TODO unit test for the property 'CallbackSecretKey'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'ConfirmationsCount'
        /// </summary>
        [Fact]
        public void ConfirmationsCountTest()
        {
            // TODO unit test for the property 'ConfirmationsCount'
        }
        /// <summary>
        /// Test the property 'FeePriority'
        /// </summary>
        [Fact]
        public void FeePriorityTest()
        {
            // TODO unit test for the property 'FeePriority'
        }
        /// <summary>
        /// Test the property 'MinimumTransferAmount'
        /// </summary>
        [Fact]
        public void MinimumTransferAmountTest()
        {
            // TODO unit test for the property 'MinimumTransferAmount'
        }
        /// <summary>
        /// Test the property 'ToAddress'
        /// </summary>
        [Fact]
        public void ToAddressTest()
        {
            // TODO unit test for the property 'ToAddress'
        }

    }

}
