/*
 * Crypto APIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: bizdev@cryptoapis.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ListOmniTokensByAddressResponseItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListOmniTokensByAddressResponseItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListOmniTokensByAddressResponseItem
        //private ListOmniTokensByAddressResponseItem instance;

        public ListOmniTokensByAddressResponseItemTests()
        {
            // TODO uncomment below to create an instance of ListOmniTokensByAddressResponseItem
            //instance = new ListOmniTokensByAddressResponseItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListOmniTokensByAddressResponseItem
        /// </summary>
        [Fact]
        public void ListOmniTokensByAddressResponseItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListOmniTokensByAddressResponseItem
            //Assert.IsType<ListOmniTokensByAddressResponseItem>(instance);
        }


        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'Frozen'
        /// </summary>
        [Fact]
        public void FrozenTest()
        {
            // TODO unit test for the property 'Frozen'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PropertyId'
        /// </summary>
        [Fact]
        public void PropertyIdTest()
        {
            // TODO unit test for the property 'PropertyId'
        }
        /// <summary>
        /// Test the property 'Reserved'
        /// </summary>
        [Fact]
        public void ReservedTest()
        {
            // TODO unit test for the property 'Reserved'
        }

    }

}
